"""
UserWord snapshot backfill — re-runs `lookup_pinyin_meaning` against
the current dictionaries and rewrites stale row snapshots in place.
"""

import pytest
from sqlalchemy import create_engine
from sqlalchemy.orm import sessionmaker
from sqlalchemy.pool import StaticPool

from app.database import Base, User, UserWord
from app.services import snapshot_backfill
from app.state import cedict_vocab, hsk_vocab


@pytest.fixture
def db_session():
    engine = create_engine(
        "sqlite:///:memory:",
        connect_args={"check_same_thread": False},
        poolclass=StaticPool,
    )
    Base.metadata.create_all(bind=engine)
    Session = sessionmaker(autocommit=False, autoflush=False, bind=engine)
    s = Session()
    s.add(User(id=1, username="alice", password_hash="x", invite_quota=0))
    s.commit()
    yield s
    s.close()


@pytest.fixture
def fake_dictionaries():
    """Stub hsk_vocab + cedict_vocab so the backfill has a known target
    to rewrite to. Restores on teardown so subsequent tests aren't
    polluted by the test fixture."""
    saved_hsk = dict(hsk_vocab)
    saved_cedict = dict(cedict_vocab)
    hsk_vocab.clear()
    cedict_vocab.clear()
    hsk_vocab.update(
        {
            "地": {
                "pinyin": "dì",
                "meaning": "earth",
                "meanings": ["earth", "ground"],
                "level_new": "new-1",
            },
        }
    )
    yield
    hsk_vocab.clear()
    hsk_vocab.update(saved_hsk)
    cedict_vocab.clear()
    cedict_vocab.update(saved_cedict)


def test_backfill_overwrites_stale_meaning(db_session, fake_dictionaries):
    db_session.add(
        UserWord(
            user_id=1,
            word="地",
            state="learning",
            pinyin="de",
            meaning="-ly",  # stale snapshot from the pre-fix parser
        )
    )
    db_session.commit()

    n = snapshot_backfill.refresh_all_user_words(db_session)
    assert n == 1

    row = db_session.query(UserWord).filter(UserWord.word == "地").one()
    assert row.meaning == "earth"
    assert row.pinyin == "dì"


def test_backfill_is_idempotent(db_session, fake_dictionaries):
    from app.database import UserWordGloss

    row = UserWord(user_id=1, word="地", state="learning", pinyin="dì", meaning="earth")
    db_session.add(row)
    db_session.commit()
    # Seed the dictionary gloss too — that's the row backfill now
    # maintains rather than the legacy columns.
    db_session.add(
        UserWordGloss(
            user_word_id=row.id,
            pinyin="dì",
            meaning="earth",
            source="dictionary",
        )
    )
    db_session.commit()

    # Snapshot already matches the dictionary — no writes expected.
    assert snapshot_backfill.refresh_all_user_words(db_session) == 0


def test_backfill_preserves_meaning_when_dictionary_has_nothing(db_session, fake_dictionaries):
    """A word not in any dictionary today should keep its existing meaning
    — pypinyin would produce a (pinyin-only, empty-meaning) fallback that
    would otherwise wipe a cached translation from an earlier session."""
    db_session.add(
        UserWord(
            user_id=1,
            word="奇怪",
            state="learning",
            pinyin="qí guài",
            meaning="strange (cached translation)",
        )
    )
    db_session.commit()

    snapshot_backfill.refresh_all_user_words(db_session)
    row = db_session.query(UserWord).filter(UserWord.word == "奇怪").one()
    # Pinyin can be regenerated by pypinyin without loss of info, but the
    # meaning should be preserved since the dictionary has nothing better.
    assert row.meaning == "strange (cached translation)"
